#Offical Nginx image from Docker Hub
FROM nginx:alpine

# Copy your static files to the Nginx web directory
COPY website/ /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80

