# Base Nginx image from Docker Hub
FROM nginx:alpine

# Copy your Application files to the Niginx HTML directory
COPY final/ /usr/share/nginx/html

# Expose port 5000 for the Nginx server
EXPOSE 5000
